Migrate database to PostgreSQL
The-Codefun-Exam-Team/Codefun-Debug pull request #69
Opened 2024-05-30 04:11 UTC by kbnopro

2024-06-28 11:30 UTC, DuCanhGH requested changes

2024-06-28 11:30 UTC, DuCanhGH commented on src/features/rankings/queries/getUsers.ts
> +          } as UserDisplayInfo;
Use `satisfies` instead of `as`.

2024-06-28 11:30 UTC, DuCanhGH commented on Dockerfile
> +COPY scripts/start_server.sh .
What's the purpose of a separate script?

2024-06-29 04:17 UTC, kbnopro commented on src/components/Score.tsx
> +      <Link href={isDisabled ? {} : `/submissions/${props.debugSubmissionId}`}>
There's no such thing as `disabled` in <a> or <Link>.

2024-06-29 04:20 UTC, kbnopro commented on src/components/Headings/types.ts
> +  extends Omit<HTMLAttributes<HTMLHeadingElement>, "classnames"> {
Oops

2024-06-29 04:29 UTC, kbnopro commented on src/features/problems/queries/getProblemCount.ts
> +  unstable_noStore();
fixed in another branch, unstable_noStore is no longer required.

2024-06-29 04:39 UTC, kbnopro commented on src/features/problems/components/InfoTable/Score.tsx
> +    return <div className="pb-4 pt-5 text-center text-2xl">Not Submitted</div>;
This is not an error but the return type from function, but I agree that errors should be thrown and handled properly.

2024-06-29 04:44 UTC, kbnopro commented on src/features/problems/actions/actionCreateProblem.ts
> +    const errors = validatedBody.error.format();
I don't see any difference, but this too will be reviewed in standardized errors.

2024-06-29 04:46 UTC, kbnopro commented on src/features/problems/actions/actionCreateProblem.ts
> +    const isAdmin = user.ok && user.user.status === "Admin";
Agree

2024-06-29 04:48 UTC, kbnopro commented on src/features/problems/actions/actionCreateProblem.ts
> +const validateInput = async ({
It's exactly what I used, but I guess u mean it shouldn't be in a separate function?

2024-06-29 06:50 UTC, DuCanhGH requested changes

2024-06-29 06:50 UTC, DuCanhGH commented on Dockerfile
> +RUN npm i -g pnpm@8.3.0
Use `corepack`.

2024-06-29 06:50 UTC, DuCanhGH commented on src/features/rankings/queries/getUsers.ts
> +  unstable_noStore();
Why both `unstable_noStore` and `unstable_cache`?

2024-07-03 15:43 UTC, DuCanhGH requested changes

2024-07-03 15:43 UTC, DuCanhGH commented on src/features/problems/actions/actionCreateProblem.ts
> +  console.log(newCode);
No astray `console.log` please.

2024-07-03 15:43 UTC, DuCanhGH commented on src/features/problems/actions/actionCreateProblem.ts
> +const validateInput = async ({
Yep.

2024-07-03 15:43 UTC, DuCanhGH commented on src/features/submissions/queries/submit.ts
> +  unstable_noStore();
This `unstable_noStore` is unnecessary.

2024-07-03 15:43 UTC, DuCanhGH commented on src/types/constants.ts
> +Object.assign(RESULTS_DICT, {
Why is this `Object.assign` necessary?

2024-07-03 16:08 UTC, kbnopro commented on src/features/problems/actions/actionCreateProblem.ts
> +const validateInput = async ({
Already fixing in [#71](https://github.com/The-Codefun-Exam-Team/Codefun-Debug/issues/71) because I need to rewrite the whole stuffs.

2024-07-03 16:13 UTC, DuCanhGH approved these changes

2024-07-03 16:13 UTC, merged